### ISSUE TITLE
상속 관계 매핑에 대해서

### ISSUE THREAD

**Issue by woo00oo** [java-dev-study/orm-jpa#15]
현재 온라인 결제 모듈 DB 스키마 구조는 거래 원장 테이블, 각 결제수단마다 거래 테이블들이 또 따로 있습니다.
예를 들어 거래 원장 테이블이 있고, 카카오페이 거래 테이블, 네이버 페이 거래 테이블 등이 있습니다. 사용자가 카카오 페이 결제를 하였을 경우 거래 원장 테이블 + 카카오페이 거래 테이블에 데이터가 저장됩니다.
스키마 구조를 개선할 수 있다고 하였을 때, 상속 관계 매핑 중 조인 전략 + 단일 테이블 전략 중 어느 전략을 가져 가는게 가장 좋은 설계가 될까요?
두 전략마다의 장 단점이 존재하여 트레이드 오프가 존재할 거 같습니다

**Comment by maggggggggggggie** [comment]
pg 업무 서비스의 구조를 잘 모르겠습니다. 
거래 원장 테이블에 결제 수단 거래 테이블에 해당되는 키 값만 저장되는 건지, 모든 거래에 대한 정보가 저장 되는 건지..
단일 테이블 전략이 조회 성능이  빠르다는 장점이나, 해당 서비스의 데이터 양이나, 테이블이 커질 경우에는 조회 성능이 느려질 수 있어 조인 전략은 어떠신가요 ?!!!!
