### ISSUE TITLE
조인 컬럼과 조인 테이블

### ISSUE THREAD

**Issue by Jo-YeonWoo** [java-dev-study/orm-jpa#19]
p.271 ~ 272에서 `조인 컬럼`과 `조인 테이블`을 사용하여 연관관계 매핑을 하는 방법에 대해 설명하고 있습니다.
`조인 컬럼`에 대한 내용은 이해가 되는데, `조인 테이블`에 대한 내용이 잘 이해가 되지 않습니다.
`FK`로 지정되어 있는 컬럼과 각 테이블의 `PK`를 매핑시켜 사용하는 것은 `조인 컬럼`과 어떤 점이 다른 건지 궁금합니다.
연관관계를 맺을 때 매핑할 `외래 키`만 모아놓은 테이블을 따로 만들고, 이 테이블에서 각각의 `PK`와 매핑시키는 방법이 `조인 테이블` 방법이 맞는 건가요...?
둘 중 `조인 컬럼` 방식을 더 많이 사용할 것 같은데, `조인 테이블` 방식을 어떤 경우에 사용할 수 있을까요?

**Comment by maggggggggggggie** [comment]
적절하게 사용 필요 !
