### ISSUE TITLE
FK 와 연관 관계 

### ISSUE THREAD

**Issue by BeomB** [java-dev-study/orm-jpa#20]
스터디를 진행하며, 최근 DBMS는 외래 키 설정을 많이 제외하고 개발을 진행한다고 들었습니다.
책을 보면 외래 키를 기준으로 연관 관계를 정하는 경우가 있는데, 외래 키 설정이 되지 않았을 경우에는 JPA를 어떻게 사용할 수 있을까요?
의미(Team과 Member)만 맞는다면 문제가 발생하지 않는 건가요?

**Comment by maggggggggggggie** [comment]
데이터의 무결성을 위해서 사용이 필요할듯하고, 무분별한 사용은 금합니다.. ! 
의미(Team과 Member)만 맞는다면 문제가 발생하지 않는 건가요? -> 그렇겠죠 !?
