### ISSUE TITLE
다대다 연결 엔티티

### ISSUE THREAD

**Issue by WonSSSIK** [java-dev-study/orm-jpa#21]
p225 다대다 연결일 경우 연결 엔티티를 두어 다대일 관계로 풀고 있는데요. 
연결 역할을 하는 Order 엔티티에  product 가 여러 개 들어 갈 수 있다면,
예를 들어 장바구니에 담기 3개의 상품을 결제 했을 때, 하나의 주문번호를 가진다면 어떻게 구현하는게 좋을까요? 
그리고 연관 관계를 공부하면서 데이터 모델링에 대해서도 학습이 필요하다고 보는데요. 지나가면서 공부를 하긴 했었지만, 
개발자는 어느 정도 수준까지 모델링에 대해 학습하는 것이 좋을까요?

**Comment by maggggggggggggie** [comment]
무한대로 공부하셔야 합니다.. !
