### ISSUE TITLE
JPA에서 직렬화

### ISSUE THREAD

**Issue by im-Lily** [java-dev-study/orm-jpa#22]
JPA 표준 스펙은 Entity에 Serializable을 구현하도록 되어 있는데, 실무에서는 거의 사용하지 않는 것으로 알고 있습니다.
혹시 실무에서 Entity에 Serializable을 구현해서 사용해 보신 분이 계실까요?

**Comment by Jo-YeonWoo** [comment]
- https://koyuchang.tistory.com/101?category=911101
- https://www.inflearn.com/questions/16570
- https://projobs.tistory.com/248
